/* ===== 算力优惠聚合 - 数据层 ===== */

/* 所有平台数据 - 含品牌色 */
const platforms = [
  // ====== 国内算力平台 ======
  { id: 'aliyun', name: '阿里云', icon: '☁️', region: 'domestic', url: 'https://www.aliyun.com', category: 'compute', brand: ['#FF6A00','#EE8200'],
    desc: '阿里云GPU云服务器，支持A100/V100/T4等多种GPU实例',
    detailDesc: '阿里云（Alibaba Cloud）是全球领先的云计算及人工智能科技公司。提供丰富的GPU云服务器实例，包括A100、V100、T4、P100等多种NVIDIA GPU型号，覆盖深度学习训练、推理、渲染等场景。PAI平台提供一站式AI开发与模型服务。新用户可享受丰富的免费试用和折扣优惠。' },
  { id: 'tencent', name: '腾讯云', icon: '💙', region: 'domestic', url: 'https://cloud.tencent.com', category: 'compute', brand: ['#006EFF','#00A3FF'],
    desc: '腾讯云GPU云服务器，TI-ONE平台提供模型训练与推理',
    detailDesc: '腾讯云提供高性能GPU云服务器，支持GN10Xp（A100）、GN7（T4）等多种GPU实例。TI-ONE平台提供从数据标注到模型训练到部署的全流程AI开发服务。面向AI开发者、科研机构和企业，提供丰富的算力选择和新用户优惠。' },
  { id: 'huawei', name: '华为云', icon: '🌊', region: 'domestic', url: 'https://www.huaweicloud.com', category: 'compute', brand: ['#CF0A2C','#E83E48'],
    desc: '华为云GPU加速型云服务器，昇腾AI云服务',
    detailDesc: '华为云提供GPU加速型云服务器和昇腾AI云服务。自研昇腾910/310 AI处理器为国产化算力方案提供强大支持。ModelArts平台是面向AI开发者的一站式开发平台，提供数据预处理、模型训练、模型部署等全流程服务，是国产化AI算力的首选平台之一。' },
  { id: 'baidu', name: '百度云', icon: '🐻', region: 'domestic', url: 'https://cloud.baidu.com', category: 'compute', brand: ['#2932E1','#3B46F0'],
    desc: '百度智能云GPU云服务器，AI算力平台',
    detailDesc: '百度智能云提供GPU云服务器、BML全功能AI开发平台和AI加速器服务。支持NVIDIA A100/V100/T4等GPU实例，同时提供百度自研的昆仑AI芯片。BML平台面向AI开发者提供从数据处理到模型训练到部署的一站式解决方案，深度整合百度的AI技术积累。' },
  { id: 'ucloud', name: 'UCloud', icon: '🔷', region: 'domestic', url: 'https://www.ucloud.cn', category: 'compute', brand: ['#1A9BF0','#4DB8FF'],
    desc: 'UCloud GPU云主机，支持A100/V100/T4，按小时计费',
    detailDesc: 'UCloud（优刻得）是国内领先的云计算服务商，提供GPU云主机、GPU托管和AI算力平台服务。支持A100/V100/T4/P40等多种GPU实例，按小时计费，灵活弹性。针对AI训练和推理场景优化网络和存储性能，是中小企业和个人开发者的高性价比选择。' },
  { id: 'qingcloud', name: '青云', icon: '🌿', region: 'domestic', url: 'https://www.qingcloud.com', category: 'compute', brand: ['#00B87A','#00D68F'],
    desc: '青云GPU云服务器，弹性高性能计算服务',
    detailDesc: '青云科技（QingCloud）提供GPU云服务器和弹性高性能计算（EHPC）服务。支持NVIDIA A100/V100/T4 GPU实例，满足AI训练、推理、渲染和高性能计算需求。按需付费，弹性扩缩容，适合各类AI和科学计算场景，尤其受到科研机构的青睐。' },
  { id: 'tencentos', name: '燧原科技', icon: '🔥', region: 'domestic', url: 'https://www.enflame-tech.com', category: 'compute', brand: ['#E8590C','#FF6B35'],
    desc: '国产AI芯片厂商，燧原云燧系列算力服务',
    detailDesc: '燧原科技（Enflame）是国产AI芯片领军企业，专注于人工智能训练和推理芯片的研发。云燧系列AI加速卡提供高性能国产化算力方案，覆盖云端训练和推理场景。作为国产替代的重要力量，燧原产品在政务、金融、运营商等行业逐步落地。' },
  { id: 'biren', name: '壁仞科技', icon: '🪨', region: 'domestic', url: 'https://www.birentech.com', category: 'compute', brand: ['#5B2C8E','#7B3FBA'],
    desc: '国产GPU厂商，壁仞BR100系列通用GPU算力',
    detailDesc: '壁仞科技（BirenTech）是国产通用GPU芯片设计企业。壁仞BR100系列通用GPU拥有强大的算力和灵活的编程能力，适用于AI训练、推理、科学计算等多种场景。作为国产GPU的重要力量，壁仞致力于构建国产智能计算生态，推动国产GPU在各行业的广泛应用。' },
  { id: 'mthreads', name: '摩尔线程', icon: '🎮', region: 'domestic', url: 'https://www.mthreads.com', category: 'compute', brand: ['#F5A623','#FFC043'],
    desc: '国产GPU厂商，MTT系列GPU云游戏与AI推理算力',
    detailDesc: '摩尔线程（MThreads）是国产GPU创新企业，MTT系列GPU覆盖云游戏、AI推理和图形渲染场景。基于MUSA架构的GPU兼容CUDA生态，降低迁移成本。面向AI推理和图形处理市场，提供国产化算力解决方案，推动国产GPU生态建设。' },
  { id: 'iluvatar', name: '天数智芯', icon: '💎', region: 'domestic', url: 'https://www.iluvatar.com', category: 'compute', brand: ['#0EA5E9','#38BDF8'],
    desc: '国产通用GPU，天垓100系列AI训练与推理加速卡',
    detailDesc: '天数智芯（Iluvatar CoreX）是国产通用GPU芯片设计企业。天垓100系列AI加速卡覆盖训练和推理场景，拥有高性能计算能力和丰富的内存带宽。支持主流AI框架，为国内AI基础设施建设提供国产化算力支撑，加速AI应用落地。' },
  { id: 'sensecraft', name: '商汤大装置', icon: '🧠', region: 'domestic', url: 'https://www.sensetime.com', category: 'compute', brand: ['#1E3A5F','#2D5A8E'],
    desc: '商汤AI大模型训练平台，SenseCore训练与推理服务',
    detailDesc: '商汤大装置（SenseCore）是商汤科技打造的AI基础设施平台，提供大规模AI训练和推理算力服务。支持万卡级分布式训练，覆盖大语言模型、多模态模型、视觉模型等。适合企业级和科研级的大规模AI训练需求，是国产AI基础设施的重要力量。' },

  // ====== 国际算力平台 ======
  { id: 'aws', name: 'AWS', icon: '🟠', region: 'international', url: 'https://aws.amazon.com', category: 'compute', brand: ['#FF9900','#FFB344'],
    desc: 'Amazon EC2 GPU实例，支持A100/H100/L4，SageMaker AI平台',
    detailDesc: 'Amazon Web Services（AWS）是全球最大的云计算平台。EC2提供丰富的GPU实例类型，包括P5（H100）、P4（A100）、G5（A10G）、G4（T4）等。SageMaker托管ML平台覆盖数据标注、训练、推理全流程。AWS Free Tier为新用户提供12个月的免费套餐，含GPU实例额度。' },
  { id: 'gcp', name: 'Google Cloud', icon: '🟢', region: 'international', url: 'https://cloud.google.com', category: 'compute', brand: ['#4285F4','#34A853'],
    desc: 'GCP GPU云实例，Vertex AI平台，TPU v5e/v4算力',
    detailDesc: 'Google Cloud Platform（GCP）提供NVIDIA GPU实例和Google自研TPU（v5e/v5p/v4）。Vertex AI平台是一站式ML工作流平台。独特优势是TPU算力，适合大规模Transformer模型训练。新用户获$300免费试用额度，涵盖所有云服务。' },
  { id: 'azure', name: 'Azure', icon: '🟦', region: 'international', url: 'https://azure.microsoft.com', category: 'compute', brand: ['#0078D4','#00A1F1'],
    desc: 'Azure GPU虚拟机，ND系列A100/H100，Azure ML平台',
    detailDesc: 'Microsoft Azure提供ND系列（A100/H100）、NC系列（K80/P100/V100）GPU虚拟机。Azure Machine Learning平台支持低代码ML开发和AutoML。深度整合OpenAI服务，提供GPT-4o等模型API。新用户获$200免费信用额度，30天内有效。' },
  { id: 'lambdalabs', name: 'Lambda Labs', icon: '🟣', region: 'international', url: 'https://lambdalabs.com', category: 'compute', brand: ['#7C3AED','#A855F7'],
    desc: '专业GPU云服务，A100/H100/H200现货，按小时/按月租赁',
    detailDesc: 'Lambda Labs是专业GPU云服务商，以现货GPU著称。提供NVIDIA H100、H200、A100、A6000等最新GPU实例，支持按小时和按月租赁。以价格透明、GPU现货充足著称，是AI创业公司和研究机构的首选GPU云之一。新用户获$50免费额度。' },
  { id: 'vastai', name: 'Vast.ai', icon: '🌐', region: 'international', url: 'https://vast.ai', category: 'compute', brand: ['#0891B2','#06B6D4'],
    desc: '去中心化GPU市场，最低价租用全球GPU资源，支持RTX4090到H100',
    detailDesc: 'Vast.ai是去中心化GPU租赁市场，连接GPU所有者和租用者。价格通常比主流云厂商低50-80%，支持从RTX4090到H100的多种GPU。按小时计费，灵活配置。适合预算有限的个人开发者和研究者，是训练和推理的高性价比选择。' },
  { id: 'runpod', name: 'RunPod', icon: '🚀', region: 'international', url: 'https://runpod.io', category: 'compute', brand: ['#0F172A','#1E293B'],
    desc: 'Serverless GPU云，按秒计费，支持A100/H100/RTX6000',
    detailDesc: 'RunPod是Serverless GPU云平台，以按秒计费和快速部署著称。支持A100/H100/RTX6000/RTX4090等GPU，提供Serverless端点（无需管理服务器）和Pod实例。特别适合模型推理部署和临时训练任务，具有自动扩缩容能力，深受开发者喜爱。' },
  { id: 'paperspace', name: 'Paperspace', icon: '📄', region: 'international', url: 'https://paperspace.com', category: 'compute', brand: ['#3B82F6','#60A5FA'],
    desc: 'GPU云计算平台，Gradient Notebook快速启动AI项目',
    detailDesc: 'Paperspace提供Gradient Notebook（托管Jupyter笔记本）和Core（GPU虚拟机）两种产品。支持A100/V100/RTX5000等GPU，提供预配置的ML环境镜像。以开发者体验优秀著称，一键启动GPU环境适合快速原型开发。新用户获$10免费额度。' },
  { id: 'coreweave', name: 'CoreWeave', icon: '☁️', region: 'international', url: 'https://www.coreweave.com', category: 'compute', brand: ['#F59E0B','#FBBF24'],
    desc: '专业云GPU服务商，A100/H100/H200，Kubernetes原生',
    detailDesc: 'CoreWeave是专业的云GPU服务商，以Kubernetes原生架构和低延迟网络著称。提供NVIDIA H200、H100、A100、L40S等最新GPU，面向AI训练和推理优化。适合Kubernetes用户和需要大规模GPU集群的企业客户，是云GPU领域的新锐力量。' },
  { id: 'huggingface', name: 'Hugging Face', icon: '🤗', region: 'international', url: 'https://huggingface.co', category: 'compute', brand: ['#FFD33D','#FFE066'],
    desc: 'ML社区+Inference API+Spaces GPU+AutoTrain',
    detailDesc: 'Hugging Face是全球最大的机器学习社区和模型托管平台。提供Inference API（托管推理）、Spaces（可部署ML应用的GPU沙箱）、AutoTrain（无代码模型训练）等服务。社区拥有20万+开源模型，是AI开发者的日常必备平台。Spaces提供免费T4 GPU实例。' },
  { id: 'together', name: 'Together AI', icon: '🤝', region: 'international', url: 'https://www.together.ai', category: 'compute', brand: ['#E11D48','#FB7185'],
    desc: '开源模型推理+训练API，按Token付费',
    detailDesc: 'Together AI提供开源大模型的推理和训练API服务。支持Llama、Mistral、DeepSeek、Qwen等100+开源模型，按Token付费，无需管理GPU基础设施。提供Chat Completions API和Embeddings API，兼容OpenAI API格式。新用户获$50免费额度。' },
  { id: 'replicate', name: 'Replicate', icon: '🔄', region: 'international', url: 'https://replicate.com', category: 'compute', brand: ['#0E7490','#0891B2'],
    desc: '云GPU推理平台，一键部署开源模型，按秒计费',
    detailDesc: 'Replicate是云GPU推理平台，让开发者可以一键部署和调用开源ML模型。平台上有5万+模型，覆盖图像生成、语言模型、音频处理等领域。提供Python/Node.js SDK，按秒计费。以其简洁的API和丰富的模型生态著称，适合快速集成AI能力。' },

  // ====== 国内大模型平台 ======
  { id: 'deepseek', name: 'DeepSeek', icon: '🔮', region: 'domestic', url: 'https://platform.deepseek.com', category: 'llm', brand: ['#4F46E5','#6366F1'],
    desc: 'DeepSeek-V3/R1大模型API，深度求索出品，极低推理价格',
    detailDesc: 'DeepSeek（深度求索）是国产大模型领军企业之一。DeepSeek-V3和DeepSeek-R1推理模型在性能上达到国际一流水平，推理成本仅为GPT-4的十分之一。API定价行业最低，新用户赠送500万Token。支持联网搜索、文件上传等功能，是开发者和企业的首选国产大模型API。' },
  { id: 'baiduernie', name: '百度文心', icon: '📖', region: 'domestic', url: 'https://yiyan.baidu.com', category: 'llm', brand: ['#2932E1','#3B46F0'],
    desc: '文心一言大模型API，ERNIE系列，百度AI云',
    detailDesc: '文心一言（ERNIE Bot）是百度自主研发的大语言模型，基于ERNIE系列预训练模型。提供文本生成、对话、翻译、写作等多种能力。百度AI云提供ERNIE系列API服务，支持企业级应用集成。每月提供100万Token免费调用额度，适合中小企业接入AI能力。' },
  { id: 'qwen', name: '阿里通义', icon: '🐰', region: 'domestic', url: 'https://tongyi.aliyun.com', category: 'llm', brand: ['#FF6A00','#EE8200'],
    desc: '通义千问大模型API，Qwen系列，阿里云百炼平台',
    detailDesc: '通义千问（Qwen）是阿里巴巴旗下的大语言模型系列，包括Qwen-Max、Qwen-Turbo、Qwen-Plus等不同规格。通过阿里云百炼平台提供API服务，支持文本生成、代码生成、数学推理等能力。开源Qwen系列模型在Hugging Face上广受欢迎，是全球最受欢迎的开源中文大模型之一。' },
  { id: 'hunyuan', name: '腾讯混元', icon: '🌀', region: 'domestic', url: 'https://hunyuan.tencent.com', category: 'llm', brand: ['#006EFF','#00A3FF'],
    desc: '腾讯混元大模型API，Hunyuan系列',
    detailDesc: '腾讯混元（Hunyuan）是腾讯自研的大语言模型，具备多轮对话、内容创作、逻辑推理等能力。通过腾讯混元API提供服务，集成在腾讯云生态中。支持文本、图像等多模态理解。新用户可领取200万Token免费额度，适合腾讯生态内的企业集成使用。' },
  { id: 'kimi', name: '月之暗面 Kimi', icon: '🌙', region: 'domestic', url: 'https://kimi.moonshot.cn', category: 'llm', brand: ['#8B5CF6','#A78BFA'],
    desc: 'Kimi大模型API，Moonshot AI，超长上下文支持',
    detailDesc: '月之暗面（Moonshot AI）推出的Kimi大模型以超长上下文处理能力著称，支持200万字以上上下文。Kimi API提供长文本理解、文档分析、信息检索等能力，特别适合处理长文档、研究报告、论文等场景。新用户赠送500万Token免费额度，是长上下文需求的首选。' },
  { id: 'glm', name: '智谱 GLM', icon: '🔬', region: 'domestic', url: 'https://open.bigmodel.cn', category: 'llm', brand: ['#059669','#10B981'],
    desc: '智谱AI GLM系列大模型API，ChatGLM/CodeGeeX',
    detailDesc: '智谱AI（Zhipu AI）是清华大学技术团队孵化的大模型企业。GLM系列包括GLM-4、GLM-4V（多模态）、CodeGeeX（代码）等。开源ChatGLM系列在全球拥有广泛用户基础。API平台提供文本生成、多模态理解、代码生成等能力。新用户赠送250万Token额度。' },
  { id: 'yi', name: '零一万物 Yi', icon: '🔢', region: 'domestic', url: 'https://platform.lingyiwanwu.com', category: 'llm', brand: ['#D97706','#F59E0B'],
    desc: '零一万物 Yi系列大模型API',
    detailDesc: '零一万物（01.AI）由前百度CEO李开复创立，Yi系列大模型在多项基准测试中表现出色。提供Yi-Lightning、Yi-Large等模型API，覆盖文本生成、推理、对话等场景。以高性价比著称，推理价格极具竞争力。新用户注册获15元体验金。' },
  { id: 'baichuan', name: '百川智能', icon: '🏔️', region: 'domestic', url: 'https://platform.baichuan-ai.com', category: 'llm', brand: ['#1D4ED8','#2563EB'],
    desc: '百川大模型API，Baichuan系列',
    detailDesc: '百川智能（Baichuan AI）由前搜狗CEO王小川创立。Baichuan系列大模型在中文理解、数学推理、代码生成等方面表现优异。开源Baichuan模型在社区广受欢迎。API平台提供文本生成和对话服务，支持企业级部署。新用户赠送100万Token免费额度。' },
  { id: 'minimax', name: 'MiniMax', icon: '🎯', region: 'domestic', url: 'https://platform.minimaxi.com', category: 'llm', brand: ['#BE123C','#E11D48'],
    desc: 'MiniMax大模型API，abab系列，Hailuo AI视频生成',
    detailDesc: 'MiniMax是国产AI大模型创业公司，abab系列大模型在文本生成和对话中表现优秀。拥有海螺AI（Hailuo AI）视频生成产品，支持文生视频和图生视频，是国内领先的AI视频生成平台。API支持文本和视频生成能力。新用户赠送100万Token额度。' },
  { id: 'doubao', name: '字节豆包', icon: '🫘', region: 'domestic', url: 'https://www.volcengine.com/product/doubao', category: 'llm', brand: ['#0B4F6C','#118AB2'],
    desc: '字节跳动豆包大模型API，火山引擎提供',
    detailDesc: '豆包大模型（Doubao）是字节跳动自主研发的大语言模型，通过火山引擎提供API服务。具备多轮对话、内容创作、知识问答等能力。深度整合字节系产品生态，在信息处理和理解方面有独特优势。新用户获赠200万Token免费额度，API定价在行业中具有竞争力。' },
  { id: 'stepfun', name: '阶跃星辰', icon: '⭐', region: 'domestic', url: 'https://www.stepfun.com', category: 'llm', brand: ['#7C2D12','#9A3412'],
    desc: '阶跃星辰Step系列大模型，文本+图像+视频多模态',
    detailDesc: '阶跃星辰（StepFun）是国产多模态大模型创新企业。Step系列大模型具备文本、图像、视频等多模态理解和生成能力。在视频理解和生成领域处于国内领先地位。API支持文本对话和图像理解能力。新用户注册赠送100万Token免费额度体验。' },

  // ====== 国际大模型平台 ======
  { id: 'openai', name: 'OpenAI', icon: '⚪', region: 'international', url: 'https://platform.openai.com', category: 'llm', brand: ['#10A37F','#19C37D'],
    desc: 'GPT-4o/GPT-4.1/GPT-4.1-mini API，最新发布nano模型',
    detailDesc: 'OpenAI是大模型领域的开创者，旗下GPT系列是全球最广泛使用的大语言模型。提供GPT-4o（多模态旗舰）、GPT-4.1（长上下文）、GPT-4.1-mini（高效）、GPT-4.1-nano（超低成本）等模型API。支持文本生成、图像理解、代码生成、函数调用等能力，是全球AI开发者的首选平台。新用户获$5免费额度。' },
  { id: 'anthropic', name: 'Anthropic', icon: '🟣', region: 'international', url: 'https://www.anthropic.com', category: 'llm', brand: ['#D946EF','#E879F9'],
    desc: 'Claude 4 Sonnet/Opus API，长上下文安全AI',
    detailDesc: 'Anthropic由前OpenAI团队创立，Claude系列大模型以安全、可靠和长上下文著称。Claude 4 Sonnet（高性价比）和Claude 4 Opus（旗舰性能）支持20万Token上下文窗口，在长文档分析、代码理解、安全对齐等领域表现卓越。新用户注册获$5免费API额度。' },
  { id: 'gemini', name: 'Google Gemini', icon: '🟦', region: 'international', url: 'https://ai.google.dev', category: 'llm', brand: ['#4285F4','#34A853'],
    desc: 'Gemini 2.5 Pro/Flash API，多模态长上下文',
    detailDesc: 'Google Gemini系列是谷歌推出的最先进多模态大模型。Gemini 2.5 Pro是旗舰推理模型，支持百万级Token上下文窗口。Gemini 2.5 Flash是高效版本。通过Google AI Studio和Vertex AI提供服务。提供慷慨的免费层（Gemini 2.0 Flash免费），是开发者的首选免费大模型API。' },
  { id: 'mistral', name: 'Mistral AI', icon: '🌫️', region: 'international', url: 'https://mistral.ai', category: 'llm', brand: ['#1E3A5F','#2D5A8E'],
    desc: 'Mistral Large/Small API，开源法式AI',
    detailDesc: 'Mistral AI来自法国，以开源高效模型著称。Mistral Large是其旗舰模型，性能对标GPT-4；Mistral Small是高效模型。提供Mistral API平台和Le Chat聊天应用。开放Mistral 7B、Mixtral 8x7B等开源模型，在全球开发者社区影响深远。提供慷慨的免费API试用层。' },
  { id: 'meta', name: 'Meta Llama', icon: '🦙', region: 'international', url: 'https://www.llama.com', category: 'llm', brand: ['#0061FE','#1877F2'],
    desc: 'Llama 4开源大模型，通过合作伙伴API提供服务',
    detailDesc: 'Meta（Facebook）开发的Llama系列是全球最具影响力的开源大模型。Llama 4支持多模态和长上下文，通过Groq、Together、Replicate、AWS Bedrock等合作伙伴API提供服务。作为开源模型，Llama系列权重可下载自行部署，适合注重数据隐私和定制化的企业场景。' },
  { id: 'groq', name: 'Groq', icon: '⚡', region: 'international', url: 'https://console.groq.com', category: 'llm', brand: ['#F97316','#FB923C'],
    desc: 'LPU推理引擎，极低延迟Llama/Mixtral/Gemma推理API',
    detailDesc: 'Groq以其自研LPU（Language Processing Unit）推理芯片闻名，提供极低延迟的大模型推理API。支持Llama 4、DeepSeek R1、Mixtral、Gemma等开源模型，推理速度是GPU的10倍以上。提供慷慨的免费API层（每天1440请求），是开发者测试和体验开源模型的首选平台。' },
  { id: 'perplexity', name: 'Perplexity', icon: '🔍', region: 'international', url: 'https://www.perplexity.ai', category: 'llm', brand: ['#1A1A2E','#16213E'],
    desc: 'Perplexity AI搜索+Sonar API，实时联网搜索推理',
    detailDesc: 'Perplexity AI以AI搜索引擎闻名，也提供Sonar系列API。Sonar API在标准LLM能力基础上整合实时联网搜索能力，让模型回答基于最新网络信息，减少幻觉。特别适合需要实时信息检索的搜索增强生成（RAG）应用场景。新用户获$5免费API额度。' },
  { id: 'cohere', name: 'Cohere', icon: '🧩', region: 'international', url: 'https://cohere.com', category: 'llm', brand: ['#6366F1','#818CF8'],
    desc: 'Cohere Command R+系列，企业级RAG与嵌入API',
    detailDesc: 'Cohere专注于企业级AI，Command R+系列在多语言理解和RAG（检索增强生成）方面表现突出。提供文本生成、嵌入（Embeddings）、分类、重排序等API，是企业构建RAG系统的首选平台之一。支持100+语言，每月提供100万Token免费调用额度。' },
  { id: 'ai21', name: 'AI21 Labs', icon: '🃏', region: 'international', url: 'https://www.ai21.com', category: 'llm', brand: ['#8B5CF6','#A78BFA'],
    desc: 'Jamba大模型API，混合SSM-Transformer架构',
    detailDesc: 'AI21 Labs是以色列AI公司，Jamba系列采用创新的混合SSM-Transformer架构，在长上下文处理上具有独特优势。Jamba 1.5支持256K上下文窗口，适合长文档分析和多轮对话。提供文本生成API服务。新用户可申请免费API试用额度。' },
  { id: 'xai', name: 'xAI Grok', icon: '🅧', region: 'international', url: 'https://x.ai', category: 'llm', brand: ['#1A1A2E','#2D2D44'],
    desc: 'xAI Grok API，Grok-2/Grok-3推理',
    detailDesc: 'xAI由Elon Musk创立，Grok系列大模型以实时知识回答和幽默风格著称。Grok-2和Grok-3提供API服务，支持实时联网搜索和推理。通过X（Twitter）平台实时数据训练，在最新事件理解上具有优势。新用户注册获$25免费API额度，可体验Grok系列全部能力。' },
];

const deals = [
// ====== 国内算力优惠 ======
  { platformId: 'aliyun', title: '新人GPU实例免费试用3个月', desc: '新用户可免费试用GPU云服务器ecs.gn6v-c10g1，含100GB数据盘，有效期3个月', tags: ['free', 'time'], validUntil: '2025-12-31', url: 'https://www.aliyun.com/daily-act/ecs/activity_selection', promoType: 'free' },
  { platformId: 'aliyun', title: 'PAI-EAS 模型服务首月5折', desc: '首次开通PAI-EAS模型在线服务，首月享受5折优惠，最高减免500元', tags: ['time'], validUntil: '2025-12-31', url: 'https://www.aliyun.com/product/bigdata/learn', promoType: 'discount' },
  { platformId: 'tencent', title: 'GPU云服务器新用户1折起', desc: '新用户购买GPU云服务器，低至1折起，可用GN10Xp/A100实例', tags: ['time'], validUntil: '2025-12-31', url: 'https://cloud.tencent.com/act/gpu', promoType: 'discount' },
  { platformId: 'tencent', title: 'TI-ONE平台免费训练额度', desc: 'TI-ONE平台新用户可领取100小时免费GPU训练时长', tags: ['free', 'new'], validUntil: '2025-12-31', url: 'https://cloud.tencent.com/product/ti-one', promoType: 'free' },
  { platformId: 'huawei', title: '昇腾AI云服务新人礼包', desc: '新用户领取昇腾AI云服务资源包，含100小时GPU实例免费使用', tags: ['free', 'new'], validUntil: '2025-12-31', url: 'https://www.huaweicloud.com/product/aiservice.html', promoType: 'free' },
  { platformId: 'huawei', title: 'ModelArts GPU算力包5折', desc: 'ModelArts平台CPU/GPU算力包购买，享受5折优惠，限时抢购', tags: ['time'], validUntil: '2025-12-31', url: 'https://www.huaweicloud.com/product/modelarts.html', promoType: 'discount' },
  { platformId: 'baidu', title: '百度AI加速器免费试用', desc: '百度AI云新用户可领取50元代金券，适用于GPU云服务器/BML/Notebook', tags: ['free'], validUntil: '2025-12-31', url: 'https://cloud.baidu.com/product/gpu.html', promoType: 'free' },
  { platformId: 'ucloud', title: 'GPU云主机新客专享', desc: '新用户首次购买GPU云主机，享受2折优惠，支持V100/T4实例', tags: ['time'], validUntil: '2025-12-31', url: 'https://www.ucloud.cn/site/product/ugpu.html', promoType: 'discount' },
  { platformId: 'qingcloud', title: '青云GPU免费试用7天', desc: '新用户可免费试用GPU云服务器7天，支持NVIDIA A100/V100实例', tags: ['free', 'time'], validUntil: '2025-12-31', url: 'https://www.qingcloud.com/products/gpu/', promoType: 'free' },
  { platformId: 'sensecraft', title: '商汤大装置训练资源试用', desc: '新用户可申请SenseCore训练平台免费试用额度，支持大规模分布式训练', tags: ['free'], validUntil: '2025-12-31', url: 'https://www.sensetime.com/cn/cloud-platform', promoType: 'free' },

  // ====== 国际算力优惠 ======
  { platformId: 'aws', title: 'AWS Free Tier GPU额度', desc: 'AWS免费套餐包含EC2 GPU实例每月750小时（t2.micro等效），新账号12个月有效', tags: ['free'], validUntil: '长期有效', url: 'https://aws.amazon.com/free', promoType: 'free' },
  { platformId: 'aws', title: 'SageMaker免费试用2个月', desc: '新用户可免费使用Amazon SageMaker每月250小时ml.t3.medium实例，共2个月', tags: ['free', 'time'], validUntil: '2025-12-31', url: 'https://aws.amazon.com/sagemaker/pricing/', promoType: 'free' },
  { platformId: 'gcp', title: 'GCP $300免费试用金', desc: '新用户注册GCP即获$300免费试用额度，适用于所有GPU服务，90天有效', tags: ['free'], validUntil: '长期有效', url: 'https://cloud.google.com/free', promoType: 'free' },
  { platformId: 'gcp', title: 'Vertex AI $300免费额度', desc: '新用户Vertex AI平台$300免费试用额度，可用于模型训练和推理', tags: ['free'], validUntil: '2025-12-31', url: 'https://cloud.google.com/vertex-ai', promoType: 'free' },
  { platformId: 'azure', title: 'Azure $200免费信用额度', desc: '新用户注册Azure即获$200免费信用额度，适用于GPU VM，30天有效', tags: ['free', 'time'], validUntil: '长期有效', url: 'https://azure.microsoft.com/free', promoType: 'free' },
  { platformId: 'azure', title: 'Azure ML免费工作区', desc: 'Azure Machine Learning免费工作区，含100小时Notebook VM使用', tags: ['free'], validUntil: '长期有效', url: 'https://azure.microsoft.com/products/machine-learning', promoType: 'free' },
  { platformId: 'lambdalabs', title: 'Lambda $50新用户试用金', desc: '新用户注册Lambda Labs即获$50免费额度，适用于所有GPU实例', tags: ['free', 'new'], validUntil: '长期有效', url: 'https://lambdalabs.com/service/gpu-cloud', promoType: 'free' },
  { platformId: 'vastai', title: 'Vast.ai 新用户$15免费', desc: '新用户在Vast.ai注册充值享$15免费额度，可租用任意GPU实例', tags: ['free', 'new'], validUntil: '长期有效', url: 'https://vast.ai/console/create', promoType: 'free' },
  { platformId: 'runpod', title: 'RunPod $10免费额度', desc: '新用户注册RunPod即获$10免费额度，体验Serverless GPU', tags: ['free', 'new'], validUntil: '长期有效', url: 'https://runpod.io/console/deploy', promoType: 'free' },
  { platformId: 'paperspace', title: 'Gradient $10免费试用', desc: '新用户Paperspace Gradient获得$10免费额度，使用免费CPU实例无时间限制', tags: ['free'], validUntil: '长期有效', url: 'https://www.paperspace.com/pricing', promoType: 'free' },
  { platformId: 'coreweave', title: 'CoreWeave新用户试用', desc: '新用户联系销售可申请$100免费GPU试用额度', tags: ['free'], validUntil: '长期有效', url: 'https://www.coreweave.com/pricing', promoType: 'free' },
  { platformId: 'huggingface', title: 'Hugging Face Spaces免费GPU', desc: 'Hugging Face Spaces提供免费CPU/GPU实例（T4 small），无限时间', tags: ['free'], validUntil: '长期有效', url: 'https://huggingface.co/spaces', promoType: 'free' },
  { platformId: 'together', title: 'Together AI $50免费额度', desc: '新用户注册Together AI即获$50免费API额度，可用于推理和训练', tags: ['free', 'new'], validUntil: '长期有效', url: 'https://www.together.ai/pricing', promoType: 'free' },
  { platformId: 'replicate', title: 'Replicate免费试用额度', desc: '新用户注册即获免费试用额度，可运行开源模型推理', tags: ['free', 'new'], validUntil: '长期有效', url: 'https://replicate.com/account/usage', promoType: 'free' },

  // ====== 国内大模型优惠 ======
  { platformId: 'deepseek', title: '新用户送500万Token', desc: 'DeepSeek新用户注册即赠送500万Token免费额度，适用于V3/R1模型', tags: ['free', 'new', 'hot'], validUntil: '长期有效', url: 'https://platform.deepseek.com', promoType: 'free' },
  { platformId: 'deepseek', title: 'DeepSeek API限时降价', desc: 'DeepSeek-V3模型API价格降至¥0.5/百万输入Token，¥2/百万输出Token，行业最低', tags: ['time', 'hot'], validUntil: '2025-12-31', url: 'https://platform.deepseek.com', promoType: 'discount' },
  { platformId: 'baiduernie', title: '文心一言免费调用', desc: '文心一言ERNIE系列API免费调用额度每月100万Token', tags: ['free'], validUntil: '长期有效', url: 'https://yiyan.baidu.com', promoType: 'free' },
  { platformId: 'qwen', title: '通义千问百万Token免费', desc: '阿里云百炼平台新用户每月免费100万Token通义千问API调用', tags: ['free', 'new'], validUntil: '长期有效', url: 'https://tongyi.aliyun.com', promoType: 'free' },
  { platformId: 'qwen', title: '通义千问限时折扣', desc: 'Qwen-Max/Turbo/Plus模型API限时折扣，部分模型降至7折', tags: ['time'], validUntil: '2025-12-31', url: 'https://tongyi.aliyun.com', promoType: 'discount' },
  { platformId: 'kimi', title: 'Kimi API新客优惠', desc: 'Moonshot AI新注册用户赠送500万Token免费额度', tags: ['free', 'new'], validUntil: '长期有效', url: 'https://kimi.moonshot.cn', promoType: 'free' },
  { platformId: 'glm', title: '智谱AI免费API额度', desc: '智谱AI GLM系列新用户赠送250万Token免费额度，含GLM-4/GLM-4V', tags: ['free', 'new'], validUntil: '长期有效', url: 'https://open.bigmodel.cn', promoType: 'free' },
  { platformId: 'yi', title: '零一万物15元体验金', desc: '新用户注册零一万物平台获15元体验金，可调用Yi系列全部模型', tags: ['free', 'new'], validUntil: '长期有效', url: 'https://platform.lingyiwanwu.com', promoType: 'free' },
  { platformId: 'minimax', title: 'MiniMax新用户赠金', desc: 'MiniMax平台新用户赠送100万Token免费额度，适用于所有模型', tags: ['free', 'new'], validUntil: '长期有效', url: 'https://platform.minimaxi.com', promoType: 'free' },
  { platformId: 'doubao', title: '豆包大模型免费试用', desc: '火山引擎豆包大模型新用户获赠200万Token免费额度', tags: ['free', 'new'], validUntil: '长期有效', url: 'https://www.volcengine.com/product/doubao', promoType: 'free' },
  { platformId: 'stepfun', title: '阶跃星辰API体验', desc: '阶跃星辰Step系列API注册即送100万Token，免费体验多模态能力', tags: ['free', 'new'], validUntil: '长期有效', url: 'https://www.stepfun.com', promoType: 'free' },
  { platformId: 'baichuan', title: '百川大模型免费Token', desc: '百川智能新注册用户赠送100万Token免费额度', tags: ['free', 'new'], validUntil: '长期有效', url: 'https://platform.baichuan-ai.com', promoType: 'free' },
  { platformId: 'hunyuan', title: '腾讯混元免费额度', desc: '腾讯混元大模型API新用户获赠200万Token免费额度', tags: ['free', 'new'], validUntil: '长期有效', url: 'https://hunyuan.tencent.com', promoType: 'free' },

  // ====== 国际大模型优惠 ======
  { platformId: 'openai', title: 'OpenAI $5免费API额度', desc: '新用户注册OpenAI平台获$5免费API调用额度，可用于GPT-4o/GPT-4.1系列', tags: ['free', 'new'], validUntil: '长期有效', url: 'https://platform.openai.com', promoType: 'free' },
  { platformId: 'openai', title: 'GPT-4.1-nano超低定价', desc: '最新GPT-4.1-nano模型仅$0.1/百万输入Token，$0.4/百万输出Token', tags: ['new', 'hot'], validUntil: '长期有效', url: 'https://platform.openai.com/docs/models', promoType: 'discount' },
  { platformId: 'anthropic', title: 'Claude $5免费额度', desc: '新用户注册Anthropic Console获$5免费API额度，可用于Claude 4系列', tags: ['free', 'new'], validUntil: '长期有效', url: 'https://www.anthropic.com', promoType: 'free' },
  { platformId: 'anthropic', title: 'Claude 4 Opus新模型发布', desc: 'Claude 4 Opus/Sonnet/Haiku全面可用，Batch API享50%折扣', tags: ['new', 'time'], validUntil: '长期有效', url: 'https://www.anthropic.com/pricing', promoType: 'discount' },
  { platformId: 'gemini', title: 'Gemini API免费层', desc: 'Google Gemini API提供免费层，每分钟60请求免费额度，Gemini 2.0 Flash免费', tags: ['free', 'new'], validUntil: '长期有效', url: 'https://ai.google.dev/pricing', promoType: 'free' },
  { platformId: 'gemini', title: 'Gemini 2.5 Pro体验', desc: 'Gemini 2.5 Pro实验版免费使用，含100万Token上下文窗口', tags: ['free', 'new', 'hot'], validUntil: '长期有效', url: 'https://ai.google.dev', promoType: 'free' },
  { platformId: 'mistral', title: 'Mistral API免费额度', desc: 'Mistral AI开发者计划提供每日免费API额度，Mistral Small完全免费', tags: ['free'], validUntil: '长期有效', url: 'https://mistral.ai', promoType: 'free' },
  { platformId: 'groq', title: 'Groq免费API层', desc: 'Groq提供免费API层，每天1440请求限制，极低延迟推理免费使用', tags: ['free'], validUntil: '长期有效', url: 'https://console.groq.com', promoType: 'free' },
  { platformId: 'groq', title: 'Groq超低推理延迟', desc: 'Groq LPU推理引擎，Llama 4/DeepSeek R1等开源模型超低延迟API', tags: ['new', 'hot'], validUntil: '长期有效', url: 'https://groq.com', promoType: 'free' },
  { platformId: 'perplexity', title: 'Perplexity $5免费额度', desc: '新用户注册Perplexity API获$5免费额度，支持Sonar联网搜索模型', tags: ['free', 'new'], validUntil: '长期有效', url: 'https://www.perplexity.ai', promoType: 'free' },
  { platformId: 'cohere', title: 'Cohere免费试用API', desc: 'Cohere提供免费API试用额度，每月100万Token免费调用', tags: ['free'], validUntil: '长期有效', url: 'https://cohere.com', promoType: 'free' },
  { platformId: 'xai', title: 'xAI Grok免费额度', desc: 'xAI Grok API新用户获赠$25免费额度，可体验Grok-2/Grok-3', tags: ['free', 'new'], validUntil: '长期有效', url: 'https://x.ai', promoType: 'free' },
  { platformId: 'meta', title: 'Llama 4通过API使用', desc: 'Meta Llama 4开源模型可通过Together/Groq/Replicate等平台免费或低价调用', tags: ['free'], validUntil: '长期有效', url: 'https://www.llama.com', promoType: 'free' },
  { platformId: 'ai21', title: 'AI21免费API层', desc: 'AI21 Labs新用户赠送免费API额度，可体验Jamba 1.5系列模型', tags: ['free', 'new'], validUntil: '长期有效', url: 'https://www.ai21.com', promoType: 'free' },
  { platformId: 'anthropic', title: 'Claude 最新定价', desc: 'Anthropic Claude 系列最新定价信息已更新', tags: ['new'], validUntil: '长期有效', url: 'https://www.anthropic.com/pricing', promoType: 'discount' },
  { platformId: 'aliyun', title: '阿里云 GPU 实例活动进行中', desc: '阿里云 GPU 云服务器新用户优惠活动持续进行', tags: ['time'], validUntil: '2025-12-31', url: 'https://www.aliyun.com/daily-act/ecs/activity_selection', promoType: 'discount' },
  { platformId: 'baidu', title: '百度智能云 GPU 产品最新活动', desc: '百度智能云 GPU 云服务器及 AI 算力平台优惠进行中', tags: ['time'], validUntil: '2025-12-31', url: 'https://cloud.baidu.com/product/gpu.html', promoType: 'discount' },
  { platformId: 'paperspace', title: 'Paperspace 优惠活动进行中', desc: 'Paperspace 当前有免费额度/试用活动，请访问官网查看详情', tags: ['free'], validUntil: '长期有效', url: 'https://www.paperspace.com/pricing', promoType: 'free' },,
  { platformId: 'deepseek', title: 'DeepSeek 最新定价', desc: 'DeepSeek 最新优惠信息已更新', tags: ['new'], validUntil: '长期有效', url: 'https://api-docs.deepseek.com/zh-cn/quick_start/pricing', promoType: 'discount' },
  { platformId: 'aliyun', title: '阿里云 GPU 活动', desc: '阿里云 最新优惠信息已更新', tags: ['new'], validUntil: '长期有效', url: 'https://www.aliyun.com/daily-act/ecs/activity_selection', promoType: 'discount' },
];
